---
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
    pandoc_args:
      - "--wrap=preserve"
always_allow_html: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_drafts") })
author: "William C. Rowden"
discussion_id: Note-on-Names
excerpt: 
layout: post
mermaid: false
tags:
  - growing up
title: Note on Names
---

```{r setup, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)

base_dir <- "~/Documents/GitHub/rowdenw.github.io"
base_url <- "/"
fig_path <- "images/draft-"

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = fig_path,
                      cache.path = '../_cache/',
                      message=FALSE, warning=FALSE,
                      cache = FALSE) # Change to TRUE for publication.
```

```{r Name-Stages, echo=FALSE}
stages_path <- file.path(base_dir, "_data", "Name-Stages.csv")
stages_df <- read.csv(stages_path, stringsAsFactors = FALSE)
stages_df %>%
  filter(E > 2) %>%
  pivot_wider(names_from = c(Version, Researcher), names_glue = "{Version} ({Researcher})",
              values_from = Name) %>%
  kable(booktabs = TRUE, caption = "Sample Title",
        escape = TRUE, format = "html") %>%
  pack_rows(index = c("Preconventional" = 1, "Conventional" = 3, "Postconventional" = 3))
```

