---
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_drafts") })
author: "William C. Rowden"
date: "2021-03-21"
discussion_id: Profile-Agile-Consultans
excerpt: ""
layout: post
mermaid: false
tags:
  - growing up
title: Profile Agile Consultants
---

```{r setup, include=FALSE}
base_dir <- "~/Documents/GitHub/rowdenw.github.io"
base_url <- "/"
fig_path <- "images/"

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = fig_path,
                      cache.path = '../_cache/',
                      message=FALSE, warning=FALSE,
                      cache = FALSE) # Change to TRUE for publication.
library(tidyverse)
library("ggthemes")
```

## Adults

```{r Cook-Greuter-Samples, echo=FALSE}
results_path <- file.path(base_dir, "_data", "Cook-Greuter-Results.csv")
samples_path <- file.path(base_dir, "_data", "Cook-Greuter-Samples.csv")

results_df <- read.csv(results_path, stringsAsFactors = FALSE)
samples_df <- read.csv(samples_path, stringsAsFactors = FALSE) %>%
  mutate(Description = paste("N=", .$Count, " ", .$Country, " ", .$Population, sep=""))
```

```{r Cook-Greuter-Mixed-Adults, echo=FALSE}
results_mixed <- results_df %>% filter(Sample == 1)
samples_mixed <- samples_df %>% filter(Sample == 1)

description <- samples_mixed$Description
joiner <- c("Enthusiast", "Operator", "Conformer", "Expert", "Achiever", "Catalyst",
            "Co-Creator", "Synergist")

ggplot(results_mixed, aes(x = Stage, y = Percentage)) + geom_point() +
  geom_line() +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  scale_y_continuous() +
  theme_tufte() +
  labs(title = description)
```

## Consultants

```{r Cook-Greuter-Results, echo=FALSE}
consultants <- results_df %>%
  filter(Sample < 4) %>%
  inner_join(samples_df, by = "Sample")
ggplot(consultants, aes(x = Stage, y = Percentage, shape=Description)) + geom_point() +
  geom_line() +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  scale_y_continuous() +
  theme_tufte() +
  labs(shape = "Sample", title = "Bell-like distribution of stages")
```

## Agile Consultant Team

```{r Distribute-Profiles, echo=FALSE}
profile_path <- file.path(base_dir, "_data", "Source-GLP.csv")
profile_df <- read.csv(profile_path, stringsAsFactors = FALSE) %>%
  select(Profile, ACN, Client, Rating, Modifier) %>%
  arrange(Rating, Modifier) %>%
  filter(ACN == TRUE, Client == TRUE) %>%
  mutate(Member = row_number())
ggplot(profile_df, aes(x = Rating, fill = factor(Rating))) + geom_bar() +
  labs(x = "Stage") +
  scale_fill_manual(values = c("6" = "orange", "7" = "green", "8" = "#008080")) +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  theme_tufte() +
  theme(legend.position = "none")
```

```{r Early, echo=FALSE}
stems_path <- file.path(base_dir, "_data", "Score-GLP.csv")
stems_df <- read.csv(stems_path, stringsAsFactors = FALSE) %>%
  inner_join(profile_df, by = "Profile") %>%
  arrange(Member, Stage) %>%
  mutate(Description = paste("Team Member", Member)) %>%
  group_by(Member) %>%
  mutate(Ogive = cumsum((Stems)))
stems <- 30
early <- stems_df %>% filter(Member == 1)
ggplot(early, aes(x = Stage, y = Ogive, color = factor(Rating))) + geom_point() +
  geom_smooth() +
  scale_color_manual("Rating",
                     labels = c("6" = "Achiever", "7" = "Catalyst", "8" = "Co-Creator"),
                     values = c("6" = "orange", "7" = "green", "8" = "#008080")) +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

```{r Late, echo=FALSE}
member_max <- profile_df[which.max(profile_df$Member), "Member"]
late <- stems_df %>% filter(Member == member_max)
ggplot(late, aes(x = Stage, y = Ogive, color = factor(Rating))) + geom_point() +
  geom_smooth() +
  scale_color_manual("Rating",
                     labels = c("6" = "Achiever", "7" = "Catalyst", "8" = "Co-Creator"),
                     values = c("6" = "orange", "7" = "green", "8" = "#008080")) +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

```{r Early+Late, echo=FALSE}
early_late <- stems_df %>% filter(Member %in% c(1, member_max))
ggplot(early_late, aes(x = Stage, y = Ogive, color=factor(Rating))) + geom_point() +
  geom_smooth() +
  scale_color_manual("Rating",
                     labels = c("6" = "Achiever", "7" = "Catalyst", "8" = "Co-Creator"),
                     values = c("6" = "orange", "7" = "green", "8" = "#008080")) +
  scale_x_continuous(labels = joiner, limits = c(2,9), n.breaks = 9) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

```{r Score-Stems, echo=FALSE}
ggplot(stems_df, aes(x = Stage, y = Ogive, color = factor(Rating))) + geom_point() +
  geom_smooth() +
  coord_cartesian(xlim=c(2,9), ylim=c(0,stems)) +
  facet_wrap(~ Member) +
  scale_color_manual("Rating",
                     labels = c("6" = "Achiever", "7" = "Catalyst", "8" = "Co-Creator"),
                     values = c("6" = "orange", "7" = "green", "8" = "#008080")) +
  theme_tufte()
```

