---
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
    pandoc_args:
      - "--wrap=preserve"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_drafts") })
author: "William C. Rowden"
date: "2021-03-21"
discussion_id: Score-Agile-Consultans
excerpt: 
layout: post
mermaid: false
tags:
  - growing up
title: Profile Agile Consultants
---

```{r setup, include=FALSE}
library(knitr)
# library(kableExtra)
library(tidyverse)
library("ggthemes")

base_dir <- "~/Documents/GitHub/rowdenw.github.io"
base_url <- "/"
fig_path <- "images/draft-"

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = fig_path,
                      cache.path = '../_cache/',
                      message=FALSE, warning=FALSE,
                      cache = FALSE) # Change to TRUE for publication.
```

```{r Early, echo=FALSE}
joiner <- c("2" = "Enthusiast", "3" = "Operator", "4" = "Conformer", "5" = "Expert",
            "6" = "Achiever", "7" = "Catalyst", "8" = "Co-Creator", "9" = "Synergist")
wilber <- c("2" = "magenta", "3" = "red", "4" = "#FFBF00", "5" = "#FFBF00",
            "6" = "orange", "7" = "green", "8" = "#008080", "9" = "turquoise")

profile_path <- file.path(base_dir, "_data", "Source-GLP.csv")
profile_df <- read.csv(profile_path, stringsAsFactors = FALSE)

stems_path <- file.path(base_dir, "_data", "Score-GLP.csv")
stems_df <- read.csv(stems_path, stringsAsFactors = FALSE)

team <- profile_df %>%
  select(Profile, ACN, Client, Rating, Modifier) %>%
  arrange(Rating, Modifier) %>%
  filter(ACN == TRUE, Client == TRUE) %>%
  mutate(Member = row_number())

team_stems <- stems_df  %>%
  inner_join(team, by = "Profile") %>%
  arrange(Member, Stage) %>%
  mutate(Description = paste("Team Member", Member)) %>%
  group_by(Member) %>%
  mutate(Ogive = cumsum((Stems)))
stems <- 30
early <- team_stems %>% filter(Member == 1)
ggplot(early) + 
  geom_col(aes(x = Stage, y = Stems, fill = factor(Stage))) +
  geom_line(aes(x = Stage, y = Ogive, color = factor(Rating))) +
  geom_point(aes(x = Stage, y = Ogive, color = factor(Rating))) +
  labs(y = "Cumulative Stems", title = early$Description) +
  scale_color_manual("Rating", values = wilber) +
  scale_fill_manual("Stage", values = wilber) +
  scale_x_continuous(breaks = 2:9, labels = joiner, limits = c(2,10)) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte() +
  theme(legend.position = "none")
```

```{r Late, echo=FALSE}
member_max <- team[which.max(team$Member), "Member"]
late <- team_stems %>% filter(Member == member_max)
ggplot(late) +
  geom_col(aes(x = Stage, y = Stems, fill = factor(Stage))) +
  geom_line(aes(x = Stage, y = Ogive, color = factor(Rating))) +
  geom_point(aes(x = Stage, y = Ogive, color = factor(Rating))) +
  labs(y = "Cumulative Stems", title = late$Description) +
  scale_color_manual("Rating", values = wilber) +
  scale_fill_manual("Stage", values = wilber) +
  scale_x_continuous(breaks = 2:9, labels = joiner, limits = c(2,10)) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte() +
  theme(legend.position = "none")
```

```{r Early+Late, echo=FALSE}
early_late <- team_stems %>% filter(Member %in% c(1, member_max))
ggplot(early_late, aes(x = Stage, y = Ogive, color = factor(Rating))) +
  geom_line() +
  geom_point() +
  labs(y = "Cumulative Stems") +
  scale_color_manual("Rating", labels = joiner, values = wilber) +
  scale_x_continuous(breaks = 2:9, labels = joiner, limits = c(2,10)) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

```{r Score-Stems, echo=FALSE}
ggplot(team_stems, aes(x = Stage, y = Ogive, color = factor(Rating))) +
  facet_wrap(~ Member)+
  geom_line() +
  geom_point() +
  labs(y = "Cumulative Stems") +
  scale_color_manual("Rating", labels = joiner, values = wilber) +
  scale_x_continuous(limits = c(2,10)) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

```{r Deliberately-Develop, echo=FALSE}
private_path <- file.path(base_dir, "_data", "Private.csv")
private_df <- read.csv(private_path, stringsAsFactors = FALSE)
multiple <- private_df %>%
  group_by(Name) %>%
  filter(n() > 1) %>%
  inner_join(profile_df)
initial <- multiple[which.min(multiple$Year), "Profile"]
subsequent <- multiple[which.max(multiple$Year), "Profile"]
comparison <- stems_df  %>%
  filter(Profile %in% c(initial, subsequent)) %>%
  inner_join(profile_df, by = "Profile") %>%
  group_by(Profile) %>%
  mutate(Ogive = cumsum((Stems)))
ggplot(comparison, aes(x = Stage, y = Ogive, color = factor(Rating))) +
  geom_line() +
  geom_point() +
  labs(y = "Cumulative Stems") +
  scale_color_manual("Rating", labels = joiner, values = wilber) +
  scale_x_continuous(breaks = 2:9, labels = joiner, limits = c(2,10)) +
  scale_y_continuous(limits = c(0,stems)) +
  theme_tufte()
```

## Conclusion

* profiling
* horizontal decalage
* deliberate development

## Notes

